apiVersion: v1
kind: Pod
metadata:
  name: download-pod
spec:
  containers:
  - name: download
    image: davidfrantz/force
    command:
      - /bin/bash
      - "-c"
      - "sleep infinity"
    workingDir: /input
    volumeMounts:
      - mountPath: /input
        name: input
      - mountPath: /data
        name: data
      - mountPath: /scripts/
        name: download-script
    securityContext:
      runAsUser: 0
  volumes:
  - name: input
    persistentVolumeClaim:
      claimName: ceph-rangeland-input
  - name: data
    persistentVolumeClaim:
      claimName: ceph-rangeland-data
  - name: download-script
    configMap:
      name: download-script
      defaultMode: 0744