kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextflow-pod-role
rules:
 - apiGroups: [""]
   resources: ["pods","pods/status","nodes"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
 - apiGroups: ["apps"]
   resources: ["daemonsets"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]