kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nextflow-pod-role
  namespace: default
rules:
 - apiGroups: [""]
   resources: ["pods","pods/status"]
   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]