apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: ceph-fs-volume
spec:
  storageClassName: cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 700G